"""
Project Euler - Problem 45
Copyright (c) Matthew Kracht. All rights reserved.

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle        Tn=n(n+1)/2     1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
import itertools

from project_euler import utils


def brute_force_solution():
    """Continue from H143 until the next triangular/pentagonal/hexagonal number is found."""
    return next(
        utils.HexagonalNumbers.term(i)
        for i in itertools.count(144)
        if (
            utils.PentagonalNumbers.has_term(utils.HexagonalNumbers.term(i)) and
            utils.TriangularNumbers.has_term(utils.HexagonalNumbers.term(i))
        )
    )


SOLUTIONS = [
    brute_force_solution,
]
